# -*- coding: utf-8 -*-
"""GenAI_V1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaoD81_QRUlR3XobD2G8UNFPsbwkjWvY

# EDA
"""

import pandas as pd

df= pd.read_csv('data_v_1.csv')

df.isna().sum()
#df.shape
#df.dtypes

# Drop rows with missing values in the Product column
df = df.dropna(subset=['Product'])

# Fill in missing values in the ECI Score column
df['ECI Score'] = df['ECI Score'].fillna(0)

# Convert the Export Country column to string dtype
df['Export Country'] = df['Export Country'].astype(str)

df = pd.melt(df, id_vars=['Product'], var_name='Export Country', value_name='ECI Score')

print(df)

df.isna().sum()

df.dtypes

"""# Gen AI Part: with Cohere Command Nightly Model"""



from langchain_experimental.agents import create_csv_agent
from langchain.llms import Cohere


agent = create_csv_agent(Cohere(temperature=0, cohere_api_key="sMtMgxOL4fxZtpW0OOFtLFraoAXCsq0FXYwoV0Xi", model = 'command-nightly'),
                         '/content/data_v_1.csv',
                         verbose=True)


#agent.cohere.llm_chain.prompt.template

# initialize the callback handler with a container to write to
from langchain.callbacks import StreamlitCallbackHandler
import streamlit as st

if prompt := st.chat_input():
    st.chat_message("user").write(prompt)
    with st.chat_message("assistant"):
        st_callback = StreamlitCallbackHandler(st.container())
        response = agent.run(prompt, callbacks=[st_callback])
        st.write(response)
