# -*- coding: utf-8 -*-
"""GenAI_V1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaoD81_QRUlR3XobD2G8UNFPsbwkjWvY

# EDA
"""

import pandas as pd

df= pd.read_csv('/content/data_v_1.csv')

df.head()

df.isna().sum()
#df.shape
#df.dtypes

# Drop rows with missing values in the Product column
df = df.dropna(subset=['Product'])

# Fill in missing values in the ECI Score column
df['ECI Score'] = df['ECI Score'].fillna(0)

# Convert the Export Country column to string dtype
df['Export Country'] = df['Export Country'].astype(str)

df = pd.melt(df, id_vars=['Product'], var_name='Export Country', value_name='ECI Score')

print(df)

df.isna().sum()

df.dtypes

"""# Gen AI Part: with Cohere Command Nightly Model"""

!pip show langchain

!pip install langchain_experimental

from langchain_experimental.agents import create_csv_agent
from langchain.llms import Cohere

!pip install cohere

agent = create_csv_agent(Cohere(temperature=0, cohere_api_key="sMtMgxOL4fxZtpW0OOFtLFraoAXCsq0FXYwoV0Xi", model = 'command-nightly'),
                         '/content/data_v_1.csv',
                         verbose=True)

agent

#agent.cohere.llm_chain.prompt.template

#My prompt
agent.run("what are the three products that morocco should invest in and export to china?")

